name: app_frontend
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  web3dart: ^2.5.0
  wallet_connect_v2: ^1.0.9
  web_socket_channel: ^3.0.3
  flutter_nfc_reader:
    git:
      url: https://github.com/matteocrippa/flutter-nfc-reader.git
      ref: master
  mobile_scanner: ^7.1.2
  mopro_flutter_package: ^0.0.1
  introduction_screen: ^4.0.0
  archive: ^4.0.7
  app_links: ^6.4.1
  flutter_nfc_kit: ^3.6.0
  nfc_manager: ^4.0.2
  dio: ^5.9.0
  http: ^1.5.0
  shared_preferences: ^2.5.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  get_it: ^8.2.0
  url_launcher: ^6.3.1
  clipboard: ^2.0.2
  provider: ^6.1.5+1
  webview_flutter: ^4.13.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Poppins/Poppins-Regular.ttf
        - asset: assets/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/Poppins/Poppins-Italic.ttf
          style: italic
  assets:
    - assets/
